%YAML 1.2
---
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2024 Jason Yundt <jason@jasonyundt.email>
-
    id: &id1 detect-bad-unicode
    name: *id1
    entry: *id1
    language: python
    types: [text]
    description: Checks to see if UTF-8 files contain “bad” code points
-
    id: &id2 flake-lock-updater
    name: *id2
    entry: *id2
    files: '(^|.*/)flake\.lock$'
    language: python
    description: >-
        Runs “nix flake update” if any inputs in flake.lock are over a
        week old.
-
    id: &id3 forbid-paths-that-match
    name: *id3
    entry: *id3
    language: python
    description: Causes an error if paths match certain regex patterns
-
    id: &id4 repo-style-checker
    name: *id4
    entry: *id4
    language: python
    pass_filenames: false
    description: Makes sure that repos follow Jason’s style for repos
-
    id: &id5 unreleased-commit-checker
    name: *id5
    entry: *id5
    language: python
    pass_filenames: false
    description: >-
        Tells you how many unreleased commits there are and gives an
        error if a release needs to be made.
