# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2026 Jason Yundt <jason@jasonyundt.email>

version = 1

[[annotations]]
# editorconfig-checker-disable
SPDX-FileCopyrightText = "2010–2026 <https://github.com/github/gitignore> contributors"
# editorconfig-checker-enable
SPDX-License-Identifier = "LicenseRef-gitignore"
path = "jasons_pre_commit_hooks_python/gitignore/**"
precedence = "override"
