# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2026 Jason Yundt <jason@jasonyundt.email>
import argparse
import importlib.resources
import io
import os
import pathlib
from typing import Any, Final

import dulwich.porcelain
import identify.identify

from . import gitignore, init


# TODO: Once we no longer support Python versions < 3.15, remove this
# next part.
try:
    frozendict
except NameError:
    def frozendict[T](obj: T) -> T:
        return obj



def main() -> None:
    init()
    ARGUMENT_PARSER: Final = argparse.ArgumentParser(
        description="""
            Automatically generates a .gitignore file based on what
            kinds of files are in the current repository. If the
            repository contains an Extra.gitignore file, then the
            contents of that file will automatically be added to the end
            of the generated .gitignore file.
        """
    )
    ARGUMENT_PARSER.parse_args()

    # See <https://git-scm.com/docs/git-commit-tree/2.55.0#_discussion>.
    # That page talks about the encoding of paths and the encoding of
    # gitignore files.
    ENCODING: Final = "utf_8"
    ERRORS: Final = "surrogateescape"

    path: bytes
    tags: set[str] = set()
    for path in dulwich.porcelain.ls_files(pathlib.Path.cwd()):
        # Most of the time, when you have a bytes object that contains a
        # path and you want to turn that path into a str, you should use
        # os.fsdecode(). Here, we don’t use os.fsdecode() because Git
        # has its own rules for the encoding of path, and those rules
        # don’t necessarily align with the rules that os.fsdecode()
        # uses.
        tags |= identify.identify.tags_from_path(
            path.decode(encoding=ENCODING, errors=ERRORS)
        )

    TEMPLATES: Final = importlib.resources.files(gitignore)
    TAG_TO_GITIGNORE_TEMPLATE: Final = frozendict({
        "nix": TEMPLATES.joinpath("Nix.gitignore"),
        "python": TEMPLATES.joinpath("Python.gitignore"),
        "rust": TEMPLATES.joinpath("Rust.gitignore")
    })
    OUTPUT_PATH: Final = pathlib.Path(".gitignore")
    file: io.Writer[str]
    # editorconfig-checker-disable
    with OUTPUT_PATH.open(mode="w", encoding=ENCODING, errors=ERRORS) as file:
        # editorconfig-checker-enable
        file.write(
            "# This file was automatically generated by "
            "gitignore-generator.\n"
            ".gitignore\n"
        )
        tag: str
        for tag in sorted(tags):
            if tag in TAG_TO_GITIGNORE_TEMPLATE:
                file.write(f"\n# {tag}:\n")
                file.write(TAG_TO_GITIGNORE_TEMPLATE[tag].read_text(
                    encoding=ENCODING,
                    errors=ERRORS
                ))
        EXTRA_GITIGNORE_PATH: Final = pathlib.Path("Extra.gitignore")
        if EXTRA_GITIGNORE_PATH.exists():
            file.write(f"\n# {EXTRA_GITIGNORE_PATH}:\n")
            file.write(EXTRA_GITIGNORE_PATH.read_text(
                encoding=ENCODING,
                errors=ERRORS
            ))
    print(f"Successfully (re)generated gitignore file: {OUTPUT_PATH}")
